import Head from "next/head";
import styles from "@/styles/Home.module.css";
import { Employment, EmploymentProps } from "@/components/Employment";

const IdegoGroupProps: EmploymentProps = {
  startDate: "September 2019",
  endDate: "March 2021",
  title: "Senior Front End Developer, Idego Group, Gdynia",
  responsibilities: [
    "Creation of new single page applications",
    "Maintenance of existing projects",
    "Teaching less experienced developers",
    "Lightning talks",
  ],
  projects: [
    {
      description: [
        `The first project that I was engaged in Idego was a greenfield one (I had
            to build it from scratch). It was a platform that offers tools for
            browsing and viewing reports, analyzes and last but not least - ratings of
            companies prepared by analysts hired by that platform.`,
        `The most challenging thing at the beginning was choosing the designs -
            because we haven't had designers onboard and needed as good UX as possible
            I aimed for some proven UI library. After many researches and comparisons
            we were convinced to use material-ui.`,
      ],
      stack: [
        "React",
        "Storybook",
        "Redux",
        "redux-saga",
        "react-router",
        "formik",
        "lodash",
        "material-ui",
        "styled-components",
        "Java/Python",
      ],
    },
    {
      description: [
        `The second project that I had a pleasure to work in was already existing,
        working platform that allows users to manage, agregate and compare social
        media records (for now Facebook and Instagram posts).`,
        `The funny part is that it was Vue project and... I have never been using
        Vue before. It's even funnier that it was not so challenging at all. Vue
        nowadays is so similar in concepts to React that you can easily jump from
        one to another.`,
        `My tasks there were connected with adding new features, refactoring
        existing spaghetticode and proposing UX upgrades to the client.`,
      ],
      stack: [
        "Vue",
        "vue-router",
        "firebase",
        "stripe.js",
        "chart.js",
        "Bootstrap",
      ],
    },
  ],
};

export default function Home() {
  return (
    <>
      <Head>
        <title>Patryk Nawolski Resume</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Roboto+Mono"
        />
      </Head>
      <main className={styles.container}>
        <section>
          <h2>About me</h2>
          <p>
            Experienced software developer with focus on front end, based in
            Warsaw. I love clean code and pay attention to modularity and
            maintainability of my solutions.
          </p>
          <p>
            I'd never copy and paste existing code without abstracting it
            somehow to make the code reusable.{" "}
            <strong className={`${styles.textUnderscored} ${styles.textLight}`}>
              I'm a developer - not a coder
            </strong>
            . I will not only produce code to implement features described by a
            PM, but also give my own advises in terms of UX of the application
            or even business solutions if I get any ideas.
          </p>
          <p>
            <strong className={`${styles.textUnderscored} ${styles.textLight}`}>
              Let's make your app great together!
            </strong>
          </p>

          <p>
            Contact:{" "}
            <a href="mailto: patryknawolski@gmail.com">
              patryknawolski@gmail.com
            </a>
            <br />
            LinkedIn:{" "}
            <a href="https://www.linkedin.com/in/patryk-nawolski-400389ab/">
              https://www.linkedin.com/in/patryk-nawolski-400389ab/
            </a>
          </p>
        </section>
        <section>
          <h2>Employment history</h2>
          <Employment {...IdegoGroupProps} />
        </section>
      </main>
    </>
  );
}
